name: 'C#/Kernel Build'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  AngouriMath:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
        
    - name: Build
      run: |
        cd Sources/AngouriMath
        dotnet build AngouriMath.csproj
        dotnet build AngouriMath.Experimental.csproj
