name: 'Solution Build'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  Everything:
    runs-on: windows-latest  # Window application cannot be run on other OS

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Build AHHHH
      run: dotnet build Sources/Samples/Samples/Playground.csproj
