name: 'Interactive Test'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  Test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Setup .NET Core 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.202

    - name: Setup .NET 6 for non-linux
      if: ${{ matrix.os != 'ubuntu-latest' }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true

    - name: Setup .NET 6 for linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo snap install dotnet-sdk --channel=6.0/beta --classic
        sudo snap alias dotnet-sdk.dotnet dotnet

    - name: Build Tests # We need it to be able to retry
      run: |
        dotnet build Sources/Tests/InteractiveWrapperUnitTests -c Release
        dotnet build Sources/Tests/TerminalUnitTests -c Release
        
    - name: Test Interactive Wrapper
      run: |
        dotnet test "Sources/Tests/InteractiveWrapperUnitTests" -c Release
        
    - name: Test Terminal Lib
      run: |
        dotnet test "Sources/Tests/TerminalUnitTests" -c Release
