name: 'Terminal nightly builds'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
 
jobs:
  TerminalBuild:
    strategy:
      matrix:
        include:
        - osflag: windows-latest
          rid: win-x64
        - osflag: ubuntu-latest
          rid: linux-x64
        - osflag: macos-latest
          rid: osx-x64
  
    runs-on: ${{ matrix.osflag }}
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.302
      
    - name: Build terminal for ${{ matrix.osflag }}
      run: |
        cd Sources/Terminal/AngouriMath.Terminal
        dotnet build -c Release -o ${{ matrix.osflag }}-publish
      
    - name: 'Upload terminal artifact for ${{ matrix.rid }}'
      uses: actions/upload-artifact@v2
      with:
        name: AngouriMath.Terminal.${{ matrix.rid }}
        path: ./Sources/Terminal/AngouriMath.Terminal/${{ matrix.osflag }}-publish
        retention-days: 14
      
      
