name: 'Terminal nightly builds'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
 
jobs:
  TerminalBuild:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
      
    - name: Build terminal for ${{ matrix.osflag }}
      run: |
        cd Sources/Terminal/AngouriMath.Terminal
        dotnet publish -c Release -r win-x64 -o win-x64-publish
        dotnet publish -c Release -r linux-x64 -o linux-x64-publish
        dotnet publish -c Release -r osx-x64 -o osx-x64-publish
    
    - name: 'Pack'
      run: |
        zip -r terminal-win-x64.zip ./Sources/Terminal/AngouriMath.Terminal/win-x64-publish
        zip -r terminal-linux-x64.zip ./Sources/Terminal/AngouriMath.Terminal/linux-x64-publish
        zip -r terminal-osx-x64.zip ./Sources/Terminal/AngouriMath.Terminal/osx-x64-publish
        
    - uses: softprops/action-gh-release@v1
      with:
        files: |
          terminal-win-x64.zip
          terminal-linux-x64.zip
          terminal-osx-x64.zip
        token: ${{ secrets.LAB_ACCESS_TOKEN }}
        tag_name: 'v1.0.0'
      env:
        GITHUB_REPOSITORY: asc-community/AngouriMathLab
