name: 'Terminal nightly builds'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
 
jobs:
  TerminalBuild:
    strategy:
      matrix:
        include:
        - osflag: windows-latest
          rid: win-x64
        - osflag: ubuntu-latest
          rid: linux-x64
        - osflag: macos-latest
          rid: osx-x64
  
    runs-on: ${{ matrix.osflag }}
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
      
    - name: Build terminal for ${{ matrix.osflag }}
      run: |
        cd Sources/Terminal/AngouriMath.Terminal
        dotnet publish -c Release -r ${{ matrix.rid }} -o ${{ matrix.osflag }}-publish
      
    # - name: 'Upload terminal artifact for ${{ matrix.rid }}'
      # uses: actions/upload-artifact@v2
      # with:
        # name: AngouriMath.Terminal.${{ matrix.rid }}
        # path: ./Sources/Terminal/AngouriMath.Terminal/${{ matrix.osflag }}-publish
        # retention-days: 14
    
    - name: 'Pack and release'
      run: |
        zip -r binaries-${{ matrix.rid }}.zip ./Sources/Terminal/AngouriMath.Terminal/${{ matrix.osflag }}-publish
        
        commithash=$(git rev-parse --short HEAD)
        currtime=$(date +%s)
        echo "commit hash is $commithash"
        echo "time is $currtime"
        name=1.0.0-terminal-master-$currtime-$commithash
        echo "name is $name"
        
        echo ${{ secrets.GITHUB_TOKEN }} > token.txt
        gh auth login --with-token < token.txt
        gh release create v1.0.0-$name 'binaries-${{ matrix.rid }}.zip#binaries-${{ matrix.rid }}' -p -R asc-community/AngouriMathLab
