name: 'Terminal nightly builds'

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'
 
jobs:
  TerminalBuild:
    strategy:
      matrix:
        osflag: [win-x64, linux-x64, osx-x64]
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.302
      
    - name: Publish terminal for ${{ matrix.osflag }}
      run: |
        cd Sources/Terminal/AngouriMath.Terminal
        dotnet publish -c Release -r ${{ matrix.osflag }} -o ${{ matrix.osflag }}-publish
      
    - name: 'Upload terminal artifact for ${{ matrix.osflag }}'
      uses: actions/upload-artifact@v2
      with:
        name: AngouriMath.Terminal.${{ matrix.osflag }}
        path: ./Sources/Terminal/AngouriMath.Terminal/${{ matrix.osflag }}-publish
        retention-days: 14
      
      
